title: Robert Richter
description: >
  Robert Richter's GitHub.IO page.
baseurl: ""
url: "https://cantido.github.io"
timezone: America/Chicago
twitter_username: Lord_Cantido
# used for the jekyll-seo-tag plugin, duplication is unfortunate
twitter:
    username: Lord_Cantido
github_username: Cantido
repository: Cantido/cantido.github.io
social:
    links:
        - https://about.me/robert.richter
        - https://www.facebook.com/rrichter
        - https://twitter.com/Lord_Cantido
        - https://www.linkedin.com/in/robertcrichter
        - https://github.com/Cantido
        - https://keybase.io/cantido
        - https://stackoverflow.com/cv/robertrichter
        - https://www.meetup.com/members/210633437/
        - https://plus.google.com/u/0/+RobertRichter1

google_site_verification: 6GGjpRMhHXMgAIyAwrOKu8obsRZE9bHif6IoZWcbzJI
google_analytics: UA-47057725-3

markdown: kramdown
theme: minima

highlighter: rouge
gems:
    - jekyll-seo-tag

exclude: [vendor] # So jekyll won't be blown up by Travis CI
