title: Rosa Richter
description: >
  Rosa Richter's GitHub.IO page.
baseurl: ""
url: "https://cantido.github.io"
timezone: America/Chicago
twitter_username: Lady_Cantido
# used for the jekyll-seo-tag plugin, duplication is unfortunate
twitter:
    username: Lady_Cantido
github_username: Cantido
repository: Cantido/cantido.github.io
social:
    links:
        - https://about.me/rosa.richter
        - https://www.facebook.com/rrichter
        - https://twitter.com/Lady_Cantido
        - https://www.linkedin.com/in/rosarichter
        - https://github.com/Cantido
        - https://keybase.io/cantido
        - https://stackoverflow.com/cv/rosarichter
        - https://www.meetup.com/members/210633437/
        - https://plus.google.com/u/0/+RosaRichter1

google_site_verification: 6GGjpRMhHXMgAIyAwrOKu8obsRZE9bHif6IoZWcbzJI
google_analytics: UA-47057725-3

markdown: kramdown
theme: jekyll-theme-minimal

highlighter: rouge
gems:
    - jekyll-seo-tag

exclude: [vendor] # So jekyll won't be blown up by Travis CI
